
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = '53df67c639f3073223ebceb93e286426840b88b5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

